import { useState, useEffect } from "react";
import { detectAIContent } from "@/src/lib/gemini";
import { Shield, Loader2, Send, User, Bot, AlertCircle } from "lucide-react";
import { motion, AnimatePresence } from "motion/react";
import { useAuth } from "../lib/AuthContext";
import { db, collection, addDoc, serverTimestamp, handleFirestoreError, OperationType } from "../lib/firebase";
import { cn } from "../lib/utils";

export function AIContentDetector({ selectedHistory }: { selectedHistory?: any }) {
  const { user } = useAuth();
  const [text, setText] = useState("");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<any>(null);

  const DEMOS = {
    ai: "The rapid advancement of artificial intelligence has revolutionized various sectors of modern society. From healthcare diagnostics to financial forecasting, machine learning algorithms are increasingly being integrated into critical decision-making processes. These systems analyze vast datasets with unprecedented speed and accuracy, identifying patterns that may be imperceptible to human observers. However, the ethical implications of such technologies remain a subject of intense debate among scholars and policymakers alike.",
    human: "I remember walking through the old park downtown last Sunday. The air was crisp, and the smell of roasted peanuts from the street vendor brought back so many memories of my childhood. I sat on that same creaky wooden bench where my grandfather used to tell me stories about the city's history. It's funny how a simple afternoon can make you feel so connected to the past and the people you've lost. I just sat there for an hour, watching the leaves fall, feeling completely at peace."
  };

  useEffect(() => {
    if (selectedHistory && selectedHistory.type === 'detection') {
      setText(selectedHistory.input);
      setResult({
        prediction: selectedHistory.prediction,
        confidence: selectedHistory.confidence,
        reason: selectedHistory.reason
      });
    }
  }, [selectedHistory]);

  const handleDetect = async () => {
    if (!text.trim()) return;
    setLoading(true);
    setResult(null);
    try {
      const res = await detectAIContent(text);
      setResult(res);

      if (user) {
        const path = "history";
        try {
          await addDoc(collection(db, path), {
            userId: user.uid,
            type: "detection",
            input: text.slice(0, 500),
            prediction: res.prediction,
            confidence: res.confidence,
            reason: res.reason,
            trustScore: res.prediction === "Human-written" ? 100 : 0, // Mock trust score for history sorting
            timestamp: serverTimestamp(),
          });
        } catch (error) {
          handleFirestoreError(error, OperationType.WRITE, path);
        }
      }
    } catch (error) {
      console.error(error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-6">
      <div className="bg-card p-6 rounded-xl border border-border shadow-sm">
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-2">
            <Bot className="w-5 h-5 text-primary" />
            <h2 className="text-xl font-semibold">AI Content Detector</h2>
          </div>
          <div className="flex gap-2">
            <button 
              onClick={() => setText(DEMOS.human)}
              className="text-[10px] uppercase tracking-wider font-bold px-2 py-1 rounded bg-secondary hover:bg-primary/20 transition-colors"
            >
              Demo: Human
            </button>
            <button 
              onClick={() => setText(DEMOS.ai)}
              className="text-[10px] uppercase tracking-wider font-bold px-2 py-1 rounded bg-secondary hover:bg-primary/20 transition-colors"
            >
              Demo: AI
            </button>
          </div>
        </div>
        <p className="text-muted-foreground text-sm mb-4">
          Determine if a piece of text was written by a human or generated by an AI.
        </p>
        
        <textarea
          value={text}
          onChange={(e) => setText(e.target.value)}
          placeholder="Paste text to detect AI generation..."
          className="w-full h-40 bg-background border border-border rounded-lg p-4 focus:ring-2 focus:ring-primary focus:outline-none transition-all resize-none"
        />
        
        <div className="flex justify-end mt-4">
          <button
            onClick={handleDetect}
            disabled={loading || !text.trim()}
            className="flex items-center gap-2 bg-primary text-primary-foreground px-6 py-2 rounded-lg font-medium hover:opacity-90 disabled:opacity-50 disabled:cursor-not-allowed transition-all"
          >
            {loading ? <Loader2 className="w-4 h-4 animate-spin" /> : <Send className="w-4 h-4" />}
            Detect AI
          </button>
        </div>
      </div>

      <AnimatePresence>
        {result && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -20 }}
            className="bg-card p-6 rounded-xl border border-border shadow-sm overflow-hidden relative"
          >
            <div className={cn(
              "absolute top-0 left-0 w-1 h-full",
              result.prediction === "AI-generated" ? "bg-red-500" : "bg-green-500"
            )} />
            
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-6">
              <div className="flex items-center gap-4">
                <div className={cn(
                  "w-12 h-12 rounded-full flex items-center justify-center",
                  result.prediction === "AI-generated" ? "bg-red-500/10 text-red-500" : "bg-green-500/10 text-green-500"
                )}>
                  {result.prediction === "AI-generated" ? <Bot className="w-6 h-6" /> : <User className="w-6 h-6" />}
                </div>
                <div>
                  <h3 className="text-lg font-bold">{result.prediction}</h3>
                  <p className="text-sm text-muted-foreground">Confidence: {result.confidence}</p>
                </div>
              </div>
              
              <div className="flex items-center gap-2 px-3 py-1 rounded-full bg-secondary text-xs font-medium">
                <AlertCircle className="w-3 h-3" />
                AI Probability: {result.prediction === "AI-generated" ? result.confidence : (100 - parseInt(result.confidence)) + "%"}
              </div>
            </div>

            <div className="space-y-2">
              <h4 className="text-sm font-semibold text-muted-foreground uppercase tracking-wider">Analysis Reason</h4>
              <div className="bg-background/50 p-4 rounded-lg border border-border text-sm leading-relaxed">
                {result.reason}
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
