import { Shield, FileText, Image as ImageIcon, Code2, Bot, HelpCircle, BookOpen, Lightbulb } from "lucide-react";

export function Documentation() {
  return (
    <div className="bg-card p-8 rounded-2xl border border-border shadow-sm max-w-4xl mx-auto">
      <div className="flex items-center gap-3 mb-8">
        <BookOpen className="w-8 h-8 text-primary" />
        <h1 className="text-3xl font-bold">Documentation</h1>
      </div>

      <div className="space-y-8 text-muted-foreground">
        <section>
          <div className="flex items-center gap-2 mb-3 text-foreground">
            <HelpCircle className="w-5 h-5 text-primary" />
            <h2 className="text-xl font-semibold">Overview</h2>
          </div>
          <p className="leading-relaxed">
            AI Guardian is a multimodal platform designed to verify the authenticity and safety of digital content. Using Google Gemini AI models, we analyze text, images, and code to provide Trust Scores and detailed findings.
          </p>
        </section>

        <section className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="p-4 rounded-xl bg-secondary/20 border border-border">
            <div className="flex items-center gap-2 mb-2 text-foreground">
              <Bot className="w-5 h-5 text-primary" />
              <h3 className="font-bold">AI Content Detection</h3>
            </div>
            <p className="text-sm">
              Paste text to determine if it was written by a human or generated by an AI. We provide a confidence score and reasoning based on linguistic patterns.
            </p>
          </div>

          <div className="p-4 rounded-xl bg-secondary/20 border border-border">
            <div className="flex items-center gap-2 mb-2 text-foreground">
              <ImageIcon className="w-5 h-5 text-primary" />
              <h3 className="font-bold">Image Analysis</h3>
            </div>
            <p className="text-sm">
              Upload images to detect deepfakes, AI-generated artifacts, or manipulated pixels. We analyze lighting, shadows, and consistency.
            </p>
          </div>

          <div className="p-4 rounded-xl bg-secondary/20 border border-border">
            <div className="flex items-center gap-2 mb-2 text-foreground">
              <FileText className="w-5 h-5 text-primary" />
              <h3 className="font-bold">Text Analysis</h3>
            </div>
            <p className="text-sm">
              Verify the factual accuracy and safety of text content. We identify potential misinformation, bias, or harmful language.
            </p>
          </div>

          <div className="p-4 rounded-xl bg-secondary/20 border border-border">
            <div className="flex items-center gap-2 mb-2 text-foreground">
              <Code2 className="w-5 h-5 text-primary" />
              <h3 className="font-bold">Code Debugger</h3>
            </div>
            <p className="text-sm">
              Submit code snippets to find bugs, security vulnerabilities, or performance bottlenecks. Get detailed suggestions for fixes.
            </p>
          </div>
        </section>

        <section>
          <div className="flex items-center gap-2 mb-3 text-foreground">
            <Shield className="w-5 h-5 text-primary" />
            <h2 className="text-xl font-semibold">Understanding Trust Scores</h2>
          </div>
          <ul className="list-disc pl-5 space-y-2">
            <li><span className="font-bold text-green-500">80-100:</span> Highly Trustworthy. Content appears authentic and safe.</li>
            <li><span className="font-bold text-yellow-500">50-79:</span> Caution Advised. Minor inconsistencies or potential AI markers found.</li>
            <li><span className="font-bold text-red-500">0-49:</span> High Risk. Significant evidence of manipulation or AI generation.</li>
          </ul>
        </section>

        <section>
          <div className="flex items-center gap-2 mb-3 text-foreground">
            <Lightbulb className="w-5 h-5 text-primary" />
            <h2 className="text-xl font-semibold">Best Practices</h2>
          </div>
          <ul className="list-disc pl-5 space-y-2">
            <li>Provide clear, high-resolution images for better analysis.</li>
            <li>Submit at least 200 words of text for more accurate AI detection.</li>
            <li>Use the Code Debugger for specific functions or logic blocks rather than entire projects.</li>
          </ul>
        </section>

        <footer className="pt-8 border-t border-border text-sm italic">
          Last updated: March 29, 2026. For further assistance, please visit our GitHub repository or contact support.
        </footer>
      </div>
    </div>
  );
}
